In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
arr.shape

(6,)

In [3]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# universal operations
arr = np.array([2,3,4,5,6])
np.sqrt(arr)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974])

In [8]:
np.exp(arr)

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ,
       403.42879349])

In [9]:
np.log(arr)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947])

In [10]:
import pandas as pd

In [11]:
# series
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [12]:
# creating series from a dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
series_dict

a    1
b    2
c    3
dtype: int64

In [1]:
data = [10,20,30]